use_frameworks!

platform :ios, '9.0'

target 'Sensors_Example' do
  pod 'Sensors', :path => '../'

  target 'Sensors_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
